server:
  port: 20001

spring:
  application:
    name: cattle-auth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/oauth?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: root

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:20001
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.security.oauth2: info
    org.springframework.security.web.FilterChainProxy: trace # 过滤器执行顺序
    org.springframework.security.web.access.ExceptionTranslationFilter: trace #异常处理
